[agent]
  debug = true
  interval = "10s"

[[inputs.gnmi]]
  addresses = ["sonic1:8080"]
  username = "admin"
  password = "admin"
  encoding = "json_ietf"
  redial = "10s"
  
  target = "sonic1"
  
  [[inputs.gnmi.subscription]]
    name = "ifcounters"
    path = "/interfaces/interface/state/counters"
    subscription_mode = "sample"
    sample_interval = "30s"

  [[inputs.gnmi.subscription]]
    name = "ifmtu"
    path = "/openconfig-interfaces:interfaces/interface/state/mtu"
    subscription_mode = "sample"
    sample_interval = "30s"
	
[[outputs.prometheus_client]]
  listen = ":9100"
  metric_version = 2
