nv set interface lo ip address 10.0.1.6/32
nv set interface lo type loopback
nv set interface swp1-4 type swp
nv set router bgp autonomous-system 65106
nv set router bgp enable on
nv set router bgp router-id 10.0.1.6
nv set vrf default router bgp address-family ipv4-unicast enable on
nv set vrf default router bgp address-family ipv4-unicast network 10.0.1.6/32
nv set vrf default router bgp address-family ipv4-unicast redistribute connected enable on
nv set vrf default router bgp address-family ipv6-unicast enable on
nv set vrf default router bgp enable on
nv set vrf default router bgp neighbor swp1 remote-as 65000
nv set vrf default router bgp neighbor swp1 type unnumbered
nv set vrf default router bgp neighbor swp2 remote-as 65000
nv set vrf default router bgp neighbor swp2 type unnumbered
nv set vrf default router bgp neighbor swp3 remote-as 65000
nv set vrf default router bgp neighbor swp3 type unnumbered
nv set vrf default router bgp neighbor swp4 remote-as 65000
nv set vrf default router bgp neighbor swp4 type unnumbered
nv config apply -y
nv config save
