#!/bin/bash

interfaces=$(ip -o link show | awk -F': ' '{print $2}')

max_length=0

for intf in $interfaces; do
    if [[ "$intf" != "lo" && ! "$intf" =~ ^veth ]]; then
        ipv4_addr=$(ip -4 addr show $intf | grep inet | awk '{print $2}')
        ipv6_addr=$(ip -6 addr show $intf | grep inet6 | awk '{print $2}' | grep -v '^fe80::')
        
        if [ -n "$ipv4_addr" ] || [ -n "$ipv6_addr" ]; then
            intf_length=${#intf}
            if [ $intf_length -gt $max_length ]; then
                max_length=$intf_length
            fi
        fi
    fi
done

extra_width=7
total_width=$((max_length + extra_width))

for intf in $interfaces; do
    if [[ "$intf" != "lo" && ! "$intf" =~ ^veth ]]; then
        ipv4_addr=$(ip -4 addr show $intf | grep inet | awk '{print $2}')
        ipv6_addr=$(ip -6 addr show $intf | grep inet6 | awk '{print $2}' | grep -v '^fe80::')
        mac_addr=$(ip link show $intf | awk '/ether/ {print $2}')
        
        if [ -n "$ipv4_addr" ] || [ -n "$ipv6_addr" ]; then
            if [ -n "$ipv4_addr" ]; then
                printf "%-${total_width}s %-20s %s\n" "$intf:" "$ipv4_addr" "$mac_addr"
            else
                printf "%-${total_width}s %-20s %s\n" "$intf:" "No IPv4 address" "$mac_addr"
            fi
            
            if [ -n "$ipv6_addr" ]; then
                printf "%-${total_width}s %-20s %s\n" " " "$ipv6_addr" " "
            fi
        fi
    fi
done
