---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: react
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/burlyluo/react-article-display.git
