---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: react
  targetNamespace: default
