nv set interface bond0 bond lacp-rate fast
nv set interface bond0 bond member swp1-2
nv set interface bond0 bond mode lacp
nv set interface bond0 link mtu 9216
nv set interface bond0 type bond
nv set interface bond0.10 base-interface bond0
nv set interface bond0.10 ipv4 address 10.1.10.100/24
nv set interface bond0.10 type sub
nv set interface bond0.10 vlan 10
nv set system hostname h1
