{{- range .Values.nodes }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes-6379.conf
    cluster-node-timeout 5000
    maxmemory 8gb
    maxmemory-policy allkeys-lru
    appendonly no
    save ""
    dir /var/lib/redis/6379
    pidfile /var/run/redis/redis-6379.pid
    logfile /var/log/redis/redis-6379.log
    bind 0.0.0.0
    daemonize no
    protected-mode no
    io-threads 1
    io-threads-do-reads no
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    repl-backlog-size 1mb
    repl-timeout 60
{{- end }}
