{{- range .Values.nodes }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}
spec:
  serviceName: {{ .name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-db-{{ .name }}@eth1
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: cluster
          command:
            - redis-server
            - /etc/redis/redis.conf
          volumeMounts:
            - name: {{ .name }}-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-data
              mountPath: /var/lib/redis/6379
            - name: redis-log
              mountPath: /var/log/redis
            - name: redis-conf-dir
              mountPath: /etc/redis
      volumes:
        - name: {{ .name }}-config
          configMap:
            name: {{ .name }}-config
        - name: redis-conf-dir
          emptyDir: {}
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-pvc
        - name: redis-log
          persistentVolumeClaim:
            claimName: redis-log-pvc
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
    - metadata:
        name: redis-log
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
{{- end }}
