frr defaults traditional
hostname r1
service integrated-vtysh-config
!
interface lo
 ip address 1.1.1.1/32
exit
!
router bgp 65001
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor eth1 interface remote-as external
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor eth1 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor eth1 activate
 exit-address-family
!
line vty
