frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface lo
 ip address 2.2.2.2/32
exit
!
router bgp 65002
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor eth1 interface remote-as external
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor eth1 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor eth1 activate
 exit-address-family
!
line vty
