nv set qos roce enable on   
nv set qos roce mode lossless

nv set qos traffic-pool roce-lossless memory-percent 50
nv set qos mapping ROCE_MAP trust both
nv set qos mapping ROCE_MAP dscp 24 switch-priority 3
nv set qos mapping ROCE_MAP dscp 26 switch-priority 3
nv set qos egress-queue-mapping default-global switch-priority 3 traffic-class 3

nv set qos pfc ROCE_PFC_PROF switch-priority 3
nv set qos pfc ROCE_PFC_PROF tx enable
nv set qos pfc ROCE_PFC_PROF rx enable

nv set qos congestion-control ROCE_ECN_PROF traffic-class 3 ecn enable
nv set qos congestion-control ROCE_ECN_PROF traffic-class 3 min-threshold 150000
nv set qos congestion-control ROCE_ECN_PROF traffic-class 3 max-threshold 300000
nv set qos congestion-control ROCE_ECN_PROF traffic-class 3 probability 100

nv set interface swp1 link state up
nv set interface swp1 link mtu 9000
nv set interface swp1 qos mapping profile ROCE_MAP
nv set interface swp1 qos pfc profile ROCE_PFC_PROF
nv set interface swp1 qos congestion-control profile ROCE_ECN_PROF

nv set interface swp1 ip address 10.1.1.1/24

nv config apply -y
nv config save -y
nv show qos roce
nv show qos mapping ROCE_MAP
nv show qos egress-queue-mapping default
nv show qos congestion-control ROCE_ECN_PROF
nv show interface swp1 qos
nv show qos pfc ROCE_PFC_PROF
