apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: nettool
    image: nginx
    #image: 192.168.2.100:5000/nettool
    securityContext:
      privileged: false
      capabilities:
        drop:
        - ALL
        add:
        - CAP_DAC_OVERRIDE
        - CAP_CHOWN
        - CAP_NET_BIND_SERVICE
