# 1. client-dev pod
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: client-dev
  name: client-dev
spec:
  containers:
  - image: 192.168.2.100:5000/nettool
    name: client-dev

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: client-prod
  name: client-prod
spec:
  containers:
  - image: 192.168.2.100:5000/nettool
    name: client-prod
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: nettool
  name: nettool
spec:
  containers:
  - image: 192.168.2.100:5000/nettool
    name: nettool

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l7-rules"
spec:
  description: "Allow HTTP GET / from env=client-dev to env= client-prod"
  endpointSelector:
    matchLabels:
      env: client-prod
  ingress:
  - fromEndpoints:
    - matchLabels:
        env: client-dev
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/"
