apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: flannel-ipip
  name: flannel-ipip
spec:
  selector:
    matchLabels:
      app: flannel-ipip
  template:
    metadata:
      labels:
        app: flannel-ipip
    spec:
      containers:
      - image: localhost:5000/nettool
        name: nettoolbox
        securityContext:
          privileged: true

---
apiVersion: v1
kind: Service
metadata:
  name: serversvc
spec:
  type: LoadBalancer 
  selector:
    app: flannel-ipip
  ports:
  - name: cni
    port: 8080
    targetPort: 80
    #nodePort: 32000
