---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: react-helm
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./deploy/helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: react
  interval: 5m0s
  targetNamespace: default
