apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: afxdp-east-network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: afxdp/myPool
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "afxdp",
      "mode": "cdq",
      "logFile": "afxdp-cni-east.log",
      "logLevel": "debug",
      "ipam": {
        "type": "host-local",
        "subnet": "10.244.1.0/24",
        "rangeStart": "10.244.1.200",
        "rangeEnd": "10.244.1.220",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.244.1.1"
      }
    }'

---
