frr version 10.5.0_git
frr defaults traditional
hostname leaf1
!
ip router-id 1.1.1.1
!
interface eth1
 ip ospf network point-to-point
exit
!
router ospf
 network 10.1.5.0/24 area 0
 network 192.168.1.0/31 area 0
exit
!
