frr version 10.5.0_git
frr defaults traditional
hostname leaf2
!
ip router-id 2.2.2.2
!
interface eth1
 ip ospf network point-to-point
exit
!
router ospf
 network 10.1.8.0/24 area 0
 network 192.168.1.2/31 area 0
exit
!
