frr version 10.5.0_git
frr defaults traditional
hostname spine
!
ip router-id 3.3.3.3
!
interface eth1
 ip ospf network point-to-point
exit
!
interface eth2
 ip ospf network point-to-point
exit
!
router ospf
 network 192.168.1.0/31 area 0
 network 192.168.1.2/31 area 0
exit
!
