apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  serviceSelector:
    matchLabels:
      app: wluo 
  nodeSelector:
    matchExpressions:
      - key: wluo
        operator: DoesNotExist
  interfaces:
  - eth0
  externalIPs: true
  loadBalancerIPs: true

