frr version 10.5.0_git
frr defaults traditional
hostname l8
!
interface lo
 ip address 10.0.1.8/32
exit
!
router bgp 65108
 bgp router-id 10.0.1.8
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 neighbor eth1 interface remote-as 65000
 no neighbor eth1 capability link-local
 neighbor eth2 interface remote-as 65000
 no neighbor eth2 capability link-local
 neighbor eth3 interface remote-as 65000
 no neighbor eth3 capability link-local
 neighbor eth4 interface remote-as 65000
 no neighbor eth4 capability link-local
 !
 address-family ipv4 unicast
  network 10.0.1.8/32
  redistribute connected
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor eth1 activate
  neighbor eth2 activate
  neighbor eth3 activate
  neighbor eth4 activate
 exit-address-family
exit
!
