frr version 10.5.0_git
frr defaults traditional
hostname s3
!
interface lo
 ip address 10.0.0.3/32
exit
!
router bgp 65000
 bgp router-id 10.0.0.3
 no bgp ebgp-requires-policy
 neighbor eth1 interface remote-as external
 no neighbor eth1 capability link-local
 neighbor eth2 interface remote-as external
 no neighbor eth2 capability link-local
 neighbor eth3 interface remote-as external
 no neighbor eth3 capability link-local
 neighbor eth4 interface remote-as external
 no neighbor eth4 capability link-local
 neighbor eth5 interface remote-as external
 no neighbor eth5 capability link-local
 neighbor eth6 interface remote-as external
 no neighbor eth6 capability link-local
 neighbor eth7 interface remote-as external
 no neighbor eth7 capability link-local
 neighbor eth8 interface remote-as external
 no neighbor eth8 capability link-local
 !
 address-family ipv4 unicast
  network 10.0.0.3/32
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor eth1 activate
  neighbor eth2 activate
  neighbor eth3 activate
  neighbor eth4 activate
  neighbor eth5 activate
  neighbor eth6 activate
  neighbor eth7 activate
  neighbor eth8 activate
 exit-address-family
exit
!
