{
 "title": "Network Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "router",
    "label": "Router",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Router Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Count by Protocol",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (protocol) (\n  count_over_time(\n    {service_name=\"router_logs\", filename=~\"$router\"}\n    | regexp `\\d{4}/\\d{2}/\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3} (?P<level>\\w+):\\s*(?P<protocol>\\w+)`\n    | protocol != \"\"\n    [${__range}]\n  )\n)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Count by Severity",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (\n  count_over_time(\n    {service_name=\"router_logs\", filename=~\"$router\"}\n    | regexp `\\d{4}/\\d{2}/\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3} (?P<level>\\w+):`\n    | level != \"\"\n    [$__range]\n  )\n)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Router Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"router_logs\", filename=~\"$router\"} |= ``"
    }
   ]
  }
 ]
}