apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "green-pool"
spec:
  cidrs:
  - cidr: "40.0.10.0/24"
  serviceSelector:
    matchLabels:
      color: green
---


apiVersion: v1
kind: Service
metadata:
  name: svc-lb-ipam
  labels:
    color: green
spec:
  type: LoadBalancer
  selector:
    color: green
  ports:
  - port: 80
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    color: green
  name: lb-ipam-1
spec:
  selector:
    matchLabels:
      color: green
  template:
    metadata:
      labels:
        color: green
    spec:
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        securityContext:
          privileged: true

