- set:
    interface:
      lo:
        ip:
          address:
            10.0.1.4/32: {}
        type: loopback
      swp1:
        type: swp
      swp2:
        type: swp
      swp3:
        type: swp
      swp4:
        type: swp
    router:
      bgp:
        autonomous-system: 65104
        enable: on
        router-id: 10.0.1.4
    vrf:
      default:
        router:
          bgp:
            address-family:
              ipv4-unicast:
                enable: on
                network:
                  10.0.1.4/32: {}
                redistribute:
                  connected:
                    enable: on
              ipv6-unicast:
                enable: on
            enable: on
            neighbor:
              swp1:
                remote-as: 65000
                type: unnumbered
              swp2:
                remote-as: 65000
                type: unnumbered
              swp3:
                remote-as: 65000
                type: unnumbered
              swp4:
                remote-as: 65000
                type: unnumbered
