- set:
    interface:
      lo:
        ip:
          address:
            10.0.0.3/32: {}
        type: loopback
      swp1:
        type: swp
      swp2:
        type: swp
      swp3:
        type: swp
      swp4:
        type: swp
      swp5:
        type: swp
      swp6:
        type: swp
      swp7:
        type: swp
      swp8:
        type: swp
    router:
      bgp:
        autonomous-system: 65000
        enable: on
        router-id: 10.0.0.3
    vrf:
      default:
        router:
          bgp:
            address-family:
              ipv4-unicast:
                enable: on
                network:
                  10.0.0.3/32: {}
              ipv6-unicast:
                enable: on
            enable: on
            neighbor:
              swp1:
                remote-as: 65101
                type: unnumbered
              swp2:
                remote-as: 65102
                type: unnumbered
              swp3:
                remote-as: 65103
                type: unnumbered
              swp4:
                remote-as: 65104
                type: unnumbered
              swp5:
                remote-as: 65105
                type: unnumbered
              swp6:
                remote-as: 65106
                type: unnumbered
              swp7:
                remote-as: 65107
                type: unnumbered
              swp8:
                remote-as: 65108
                type: unnumbered
