{
 "title": "FRR Exporter - BGP",
 "description": "BGP metrics from https://github.com/tynany/frr_exporter",
 "tags": [
  "frr",
  "bgp"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "afi",
    "label": "Protocol",
    "query": {
     "query": "label_values(frr_bgp_peer_state,afi)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(frr_bgp_peer_state,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Peer State History",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "frr_bgp_peer_state{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "{{peer_desc}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frr_bgp_peers_count_total{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Groups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frr_bgp_peer_groups_count_total{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Routing Table Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frr_bgp_rib_memory_bytes{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "frr_bgp_peer_state{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "State"
    },
    {
     "expr": "frr_bgp_peer_prefixes_received_count_total{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "frr_bgp_peer_prefixes_advertised_count_total{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "frr_bgp_peer_uptime_seconds{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frr_bgp_peers_memory_bytes{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Routes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frr_bgp_rib_count_total{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Update Rate",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "irate(frr_bgp_peer_message_received_total{afi=\"$afi\",instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{peer_desc}}"
    }
   ]
  },
  {
   "title": "BGP Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "irate(frr_bgp_peer_message_received_total{afi=\"$afi\",instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{peer_desc}}"
    },
    {
     "expr": "-irate(frr_bgp_peer_message_sent_total{afi=\"ipv4\",instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{peer_desc}}"
    }
   ]
  }
 ]
}