apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: calico-vxlan-crosssubnet
  name: calico-vxlan-crosssubnet
spec:
  selector:
    matchLabels:
      app: calico-vxlan-crosssubnet
  template:
    metadata:
      labels:
        app: calico-vxlan-crosssubnet
    spec:
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: serversvc
spec:
  type: NodePort
  selector:
    app: calico-vxlan-crosssubnet
  ports:
  - name: calico-vxlan-crosssubnet
    port: 8080
    targetPort: 80
    nodePort: 32000
