hostname s2
service routing protocols model multi-agent
interface Ethernet1
   no switchport
   ip address 10.0.0.2/31
interface Ethernet2
   no switchport
   ip address 10.0.0.6/31
interface Loopback0
   ip address 4.4.4.4/32
interface Management0
   ip address 172.20.20.6/24
ip routing
router bgp 65001
   router-id 4.4.4.4
   neighbor PG_LEAVES peer group
   neighbor PG_LEAVES remote-as 65101
   neighbor 10.0.0.3 peer group PG_LEAVES
   neighbor 10.0.0.7 peer group PG_LEAVES
   address-family ipv4
      neighbor PG_LEAVES activate
      network 4.4.4.4/32

