! Startup-config last modified at Wed Apr 22 04:28:12 2026 by root
! device: l1 (cEOSLab, EOS-4.36.0F-47083774.4360F (engineering build))
!
no aaa root
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname l1
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
vlan 10,4094
!
interface Port-Channel10
   switchport trunk allowed vlan 10,4094
   switchport mode trunk
!
interface Port-Channel20
   switchport access vlan 10
   mlag 20
!
interface Ethernet1
   channel-group 10 mode active
!
interface Ethernet2
   switchport access vlan 10
   channel-group 20 mode active
   lacp timer fast
!
interface Ethernet3
   channel-group 10 mode active
!
interface Ethernet4
   channel-group 10 mode active
!
interface Ethernet5
   no switchport
   ip address 10.0.0.1/31
!
interface Ethernet6
   no switchport
   ip address 10.0.0.3/31
!
interface Management0
   ip address 172.20.20.3/24
   ipv6 address 3fff:172:20:20::3/64
!
interface Vlan10
   ip address 10.1.8.2/24
   ip virtual-router address 10.1.8.1
!
interface Vlan4094
   no autostate
   ip address 1.1.1.1/30
!
ip virtual-router mac-address 00:1c:73:00:00:99
!
ip routing
!
mlag configuration
   domain-id MLAG_LAB
   local-interface Vlan4094
   peer-address 1.1.1.2
   peer-address heartbeat 172.20.20.4
   primary-priority 10
   peer-link Port-Channel10
   dual-primary detection delay 30 action errdisable all-interfaces
   dual-primary recovery delay mlag 60 non-mlag 0
!
router bgp 65101
   router-id 1.1.1.1
   neighbor PG_SPINES peer group
   neighbor PG_SPINES remote-as 65001
   neighbor 10.0.0.0 peer group PG_SPINES
   neighbor 10.0.0.2 peer group PG_SPINES
   !
   address-family ipv4
      neighbor PG_SPINES activate
      network 10.1.8.0/24
!
end
