hostname s1
service routing protocols model multi-agent
interface Ethernet1
   no switchport
   ip address 10.0.0.0/31
interface Ethernet2
   no switchport
   ip address 10.0.0.4/31
interface Ethernet3
   no switchport
   ip address 10.1.9.1/24
interface Loopback0
   ip address 3.3.3.3/32
interface Management0
   ip address 172.20.20.5/24
ip routing
router bgp 65001
   router-id 3.3.3.3
   neighbor PG_LEAVES peer group
   neighbor PG_LEAVES remote-as 65101
   neighbor 10.0.0.1 peer group PG_LEAVES
   neighbor 10.0.0.5 peer group PG_LEAVES
   address-family ipv4
      neighbor PG_LEAVES activate
      network 3.3.3.3/32
      network 10.1.9.0/24

