log file /etc/frr/frr.log debug

debug zebra vxlan
debug bgp neighbor-events
debug bgp updates

vrf red
 vni 100
exit-vrf
!

interface bond0
 description ES-B (vm2+vm4) all-active
 evpn mh es-id 2
 evpn mh es-sys-mac 44:38:39:ff:00:02
 evpn mh es-df-pref 500
!

router bgp 64513
 bgp router-id 100.65.0.3
 no bgp ebgp-requires-policy
 no bgp network import-check
 no bgp default ipv4-unicast

 neighbor 192.168.10.4 remote-as 64612

 address-family ipv4 unicast
  neighbor 192.168.10.4 activate
  network 100.65.0.3/32
 exit-address-family

 address-family l2vpn evpn
  neighbor 192.168.10.4 activate
  rd 100.65.0.3:3
  route-target import auto
  route-target export auto
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
exit
!

router bgp 64513 vrf red
 bgp router-id 100.65.0.3
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
 exit-address-family
exit
!
